### PR TITLE
Added submodule theme4/XS101/CHAP-Training-Examples-Materials

### PR DESCRIPTION
**Pull request by wernersun**
The repo with hands-on tutorial examples for XS101 (https://github.com/CHESSComputing/CHAP-Training-Examples-Materials.git) was added as a submodule to the theme4/XS101 folder.

### CODE REVIEW

**Comment by sajith** [comment]
@wernersun Thank you Werner!

I'm assuming that we want content from the submodule included in https://xcitecourse.org. When I tried to run `quarto render`, I encountered a little problem.  Quarto does not like empty files:

```
ERROR: 500 (Internal Error): Unexpected end of JSON input
[1/3] theme4/XS101/CHAP-Training-Examples-Materials/example_03/visualize.ipynb
ERROR: SyntaxError: Unexpected end of JSON input
```

This is a known issue (https://github.com/quarto-dev/quarto-cli/issues/6392).  Would you mind adding a title to that empty notebook, just to get around this issue?

We will also need to (1) add a way to navigate to this content, and (2) check out the submodule from the [publish workflow](https://github.com/RENCI-NRIG/X-CITE/blob/main/.github/workflows/publish.yml).  I can do that once Quarto is able to render the content without problems.

If you simply want to add the submodule and not bother with the website, that is fine too. :-)

**Comment by wernersun** [comment]
@sajith Thanks, Sajith!

I have removed the empty visualize.ipynb files -- hopefully that fixes the render. For now, let's omit the submodule from the website. We can discuss further offline.

**Comment by wernersun** [comment]
@sajith Sorry, I only intended to add a commit to this pull request, not merge it into the main branch. I hope I did not break anything.

**Comment by sajith** [comment]
@wernersun Don't worry, it has not broken anything. The publish workflow does deploy from main branch when something is merged, but it does not check out submodules yet. :-)

**Pull request merged**
