### PR TITLE
moving NumPy into PE102 where it belongs.

### PR DESCRIPTION
**Pull request by erikscott**
PE101 is for packages in general and conda. Moved to PE102 Numerical analysis.

### CODE REVIEW

**Comment by sajith** [comment]
We also need a way to navigate to this file, either by editing `/index.md` or renaming this file (with `git mv -f theme1/PE102/PE102-02NumPy.ipynb theme1/PE102/numerical-data-analysis.ipynb`).

We also need a way to render the cells when deploying to the site.  We'll need numpy and matplotlib on CI.  I will take care of that.

**Comment by sajith** [comment]
Actually, Quarto will not execute the notebooks by default because "the presumption being that you have already executed them while editing the notebook".

https://quarto.org/docs/projects/code-execution.html#notebooks

There are execution errors in https://github.com/RENCI-NRIG/X-CITE/blob/main/theme1/PE102/PE102-02NumPy.ipynb.  We should re-run the notebook locally again, fixing those errors, and commit those changes.

**Comment by erikscott** [comment]
That notebook has a dependency on matplotlib. Is that the problem?
Erik


________________________________________

**Comment by sajith** [comment]
It should not be a problem if we've executed cells in the notebook locally.  If we want, we can install numpy and matplotlib on CI, and get the workflows to execute them on CI. But that is not really necessary, at least right now.

**Comment by erikscott** [comment]
There was a typo in a package alias name. NumPy is already there, no problem. I took out the example with matplotlib, it was really just left over from some previous lab exercise.

________________________________________

**Pull request merged**
